ignore:
- "./cadence/contracts/example-assets/*"
- "./cadence/contracts/utils/ArrayUtils.cdc"
- "./cadence/contracts/utils/StringUtils.cdc"
- "./cadence/contracts/utils/ScopedFTProvider.cdc"
- "./cadence/contracts/standards/Burner.cdc"
- "./cadence/contracts/standards/FlowStorageFees.cdc"
- "./cadence/contracts/standards/FlowToken.cdc"
- "./cadence/contracts/standards/FungibleToken.cdc"
- "./cadence/contracts/standards/FungibleTokenMetadataViews.cdc"
- "./cadence/contracts/standards/NonFungibleToken.cdc"
- "./cadence/contracts/standards/ViewResolver.cdc"
- "./cadence/contracts/templates/emulator/*"
- "./cadence/contracts/templates/previewnet/*"
- "./cadence/contracts/test/*"